import type { Metadata } from "next";
import {Ubuntu, Ubuntu_Mono} from 'next/font/google';
import "./globals.css";
import {Footer} from "@/components/layout/Footer";

const geistSans = Ubuntu({
    weight: "400",
    variable: "--font-ubuntu",
  subsets: ["latin"]
});

const geistMono = Ubuntu_Mono({
    weight: "400",
    variable: "--font-ubuntu",
    subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "QR Menü",
  description: "Generated by sagalas.com.tr",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
